name: Publish Release

on:
  push:

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools twine

      - name: Build and Publish
        run: |
          clear && rm -r -f build ag_data_lib.egg-info dist &&
          python setup.py sdist bdist_wheel &&
          twine check dist/* &&
          mkdir ./dist/release &&
          cp dist/*.tar.gz dist/release/ag-data-lib.tar.gz

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DATA_LIB_SECRET }}
        with:
          tag_name: v${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - Bug fixes and improvements.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DATA_LIB_SECRET}}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/release/ag-data-lib.tar.gz
          asset_name: ag-data-lib.tar.gz
          asset_content_type: application/gzip
